name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.16.0
  firebase_auth: ^4.16.0      # Use the latest stable version
  cloud_firestore: ^4.6.0     # Use the latest stable version
  cupertino_icons: ^1.0.8
  google_fonts: ^2.3.2   
  carousel_slider: ^4.0.0     

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/coffeelogo.png 
    - images/banner.png
    - images/coffee1.png
    - images/coffee2.png
    - images/coffee3.png
    - images/coffee4.png
